//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siterm.WPF {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siterm.WPF.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zusätzliche Informationen ähnelt.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternative Name ähnelt.
        /// </summary>
        public static string AlternativeNames {
            get {
                return ResourceManager.GetString("AlternativeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereich ähnelt.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zweiwöchig ähnelt.
        /// </summary>
        public static string Biweekly {
            get {
                return ResourceManager.GetString("Biweekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zweijährig ähnelt.
        /// </summary>
        public static string Biyearly {
            get {
                return ResourceManager.GetString("Biyearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verantwortlicher ähnelt.
        /// </summary>
        public static string Chief {
            get {
                return ResourceManager.GetString("Chief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kommentar ähnelt.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angelegt am ähnelt.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterweisung anlegen ähnelt.
        /// </summary>
        public static string CreateInstructionBtn {
            get {
                return ResourceManager.GetString("CreateInstructionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Unterweisung für: ähnelt.
        /// </summary>
        public static string CreateInstructionForLabel {
            get {
                return ResourceManager.GetString("CreateInstructionForLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anlage bearbeiten ähnelt.
        /// </summary>
        public static string EditDeviceLabel {
            get {
                return ResourceManager.GetString("EditDeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereich ähnelt.
        /// </summary>
        public static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereiche / Anlagen ähnelt.
        /// </summary>
        public static string FacilityTabHeader {
            get {
                return ResourceManager.GetString("FacilityTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erste Hilfe ähnelt.
        /// </summary>
        public static string FirstAidTabHeader {
            get {
                return ResourceManager.GetString("FirstAidTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorname ähnelt.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemein ähnelt.
        /// </summary>
        public static string GeneralTabHeader {
            get {
                return ResourceManager.GetString("GeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Halbjährlich ähnelt.
        /// </summary>
        public static string HalfYearly {
            get {
                return ResourceManager.GetString("HalfYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ibf.rwth-aachen.de ähnelt.
        /// </summary>
        public static string HomeEmailEnding {
            get {
                return ResourceManager.GetString("HomeEmailEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die H-Sätze ähnelt.
        /// </summary>
        public static string HSentences {
            get {
                return ResourceManager.GetString("HSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterwiesene ähnelt.
        /// </summary>
        public static string Instructed {
            get {
                return ResourceManager.GetString("Instructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Außer (Tätigkeit/Maschine): ähnelt.
        /// </summary>
        public static string InstructionExceptForLabel {
            get {
                return ResourceManager.GetString("InstructionExceptForLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur (Tätigkeit/Maschine): ähnelt.
        /// </summary>
        public static string InstructionOnlyForLabel {
            get {
                return ResourceManager.GetString("InstructionOnlyForLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterweisungen ähnelt.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterweisender ähnelt.
        /// </summary>
        public static string Instructor {
            get {
                return ResourceManager.GetString("Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geprüft ähnelt.
        /// </summary>
        public static string IsDone {
            get {
                return ResourceManager.GetString("IsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachname ähnelt.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Schulung ähnelt.
        /// </summary>
        public static string LastTraining {
            get {
                return ResourceManager.GetString("LastTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IBF - Sicherheitsterminal ähnelt.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monatlich ähnelt.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Unterweisung ähnelt.
        /// </summary>
        public static string NewInstructionBtn {
            get {
                return ResourceManager.GetString("NewInstructionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Wartung ähnelt.
        /// </summary>
        public static string NewServiceReportBtn {
            get {
                return ResourceManager.GetString("NewServiceReportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nächste Schulung ähnelt.
        /// </summary>
        public static string NextTraining {
            get {
                return ResourceManager.GetString("NextTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bisher keine Unterweisungen angelegt ähnelt.
        /// </summary>
        public static string NoInstructionsYet {
            get {
                return ResourceManager.GetString("NoInstructionsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bisher keine Wartungen angelegt ähnelt.
        /// </summary>
        public static string NoServiceReportsYet {
            get {
                return ResourceManager.GetString("NoServiceReportsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist kein Signaturpad angeschlossen. Bitte Verbindung überprüfen. ähnelt.
        /// </summary>
        public static string NoSignaturePadExceptionMessage {
            get {
                return ResourceManager.GetString("NoSignaturePadExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Signaturpad ähnelt.
        /// </summary>
        public static string NoSignaturePadExceptionTitle {
            get {
                return ResourceManager.GetString("NoSignaturePadExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfad ähnelt.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon ähnelt.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die P-Sätze ähnelt.
        /// </summary>
        public static string PSentences {
            get {
                return ResourceManager.GetString("PSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vierteljährlich ähnelt.
        /// </summary>
        public static string QuarterYearly {
            get {
                return ResourceManager.GetString("QuarterYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll die Unterschrifteingabe nochmal wiederholt werden? Bei Abbruch wird keine Datei angelegt. Sollte die Unterschrift für mehrere Dateien nötig sein (Unterweisender) wird keine angelegt. ähnelt.
        /// </summary>
        public static string RetrySignatureMessage {
            get {
                return ResourceManager.GetString("RetrySignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiederholen? ähnelt.
        /// </summary>
        public static string RetrySignatureTitle {
            get {
                return ResourceManager.GetString("RetrySignatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie eine Maschine aus. ähnelt.
        /// </summary>
        public static string SelectDeviceMainText {
            get {
                return ResourceManager.GetString("SelectDeviceMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durch die Auswahl einer Maschine in der Baumstruktur werden weitere Informationen bereitgestellt. ähnelt.
        /// </summary>
        public static string SelectDeviceSubText {
            get {
                return ResourceManager.GetString("SelectDeviceSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie einen Gefahrstoff aus. ähnelt.
        /// </summary>
        public static string SelectSubstanceMainText {
            get {
                return ResourceManager.GetString("SelectSubstanceMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durch die Auswahl eines Gefahrstoffes in der Baumstruktur werden weitere Informationen bereitgestellt. ähnelt.
        /// </summary>
        public static string SelectSubstanceSubText {
            get {
                return ResourceManager.GetString("SelectSubstanceSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wartungen ähnelt.
        /// </summary>
        public static string ServiceReports {
            get {
                return ResourceManager.GetString("ServiceReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gefahrstoffe ähnelt.
        /// </summary>
        public static string SubstanceTabHeader {
            get {
                return ResourceManager.GetString("SubstanceTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gültigkeit ähnelt.
        /// </summary>
        public static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gültig bis ähnelt.
        /// </summary>
        public static string ValidTill {
            get {
                return ResourceManager.GetString("ValidTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wöchentlich ähnelt.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jährlich ähnelt.
        /// </summary>
        public static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
